name: tasksphere_monitor
description: App Flutter para monitorar TaskSphere
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  graphql_flutter: ^5.2.0-beta.6
  http: ^0.13.6
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/tasksphere-logo.png"
  adaptive_icon_background: "#0F0326"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
